### ISSUE TITLE
Find and study existing system implementation

### ISSUE THREAD

**Issue by xvaisr** [xvaisr/SINproject#3]
Je potreba najit nejaky realny system ridici veci, ktere budeme symulovat. Jaky sytem to bude je zavysle na prechozim issue [#2].

**Comment by xvaisr** [comment]
Assigned to:  @trepik & @OndrejBlucha

**Comment by trepik** [comment]
Nasel jsem docela hutnyresearch paper na tuto temu bude to stacit podle vas? [Cooperative cleaning robots](http://web.media.mit.edu/~yanival/IJRR1.pdf)

**Comment by xvaisr** [comment]
Nepotrebujeme research paper (tedy alespon zatim), ale potrebujeme implementujici system. Cetl jsi readme ? Potrebujem nejaky existujici ridici system (napriklad to co on ma v zadani http://domoticz.com/) ktery je schopny ridit nejake takove roboty a vyresit jakym zpusobem ho napojit na JADE - pro me preferovany framework. Jelikoz nemame k dispozici inteligentni budovu nebo roboty samotne, tak potrebujeme vytvorit symulaci ... Ta bude prave v JADE. Ale rizeni musi realizovat nejaky existujici system. Co se po vas chce momentalne je omrknotu ten domoticz nebo se poohlednout i po necem jinem co by se dalo pouzit na zadanou ulohu a prijit na to jak to propojit se symulaci v JADE ...

**Comment by trepik** [comment]
All right ten demoticz stoji za prd ale nasel jsem slusnou nahradu [Haystack](http://project-haystack.org/) Doporucuji zkouknout [intprduction video](https://www.youtube.com/watch?v=5C6GwLbYqTw) 
Je to open source a maji to i v Jave, coz je pro nas idealni.
