### ISSUE TITLE
Register our team

### ISSUE THREAD

**Issue by trepik** [xvaisr/SINproject#4]
Here are the instructions for registration: "Každý projekt musí být na začátku registrován a na konci demonstrován. Registrace se provede odevzdáním krátkého abstraktu, ve kterém bude popsáno, jak si řešitelé upřesnili příslušnou variantu zadání a co bude výsledkem. Abstrakt bude pojmenován stejně jako budoucí zazipovaný projekt, jen místo přípony .zip bude buď .pdf nebo .txt. Registrace i odevzdání projektu proběhne přes informační systém FIT, kde budou uvedeny i termíny. Není chybou, když se projekt v průběhu řešení odchýlí od registovaného abstraktu. Ten slouží k počátečnímu zorientování a k případnému předběžnému plánovaní demonstrací. Definitivní plán vznikne až po definitivním odevzdání projektů. O formě demonstrace rozhodne v jednotlivých případech vyučující." Although the registration is closed right now Mr. Janousek told us today that he is gonna open the registrations for one more week.
Me and @OndrejBlucha agreed on the cleaning robots topic. It could be further discussed in that [issue](https://github.com/xvaisr/SINproject/issues/2)
@xvaisr would you register our team once we agree on the topic?

**Comment by xvaisr** [comment]
I need your logins ...

**Comment by xvaisr** [comment]
Our team is registered with abstract I uploaded to WIS as well as into this repo. abb3d4ec29feec420b2c661e2061fddcc9d421e0
