### ISSUE TITLE
Divide and Conquer (rozdeleni prace)

### ISSUE THREAD

**Issue by trepik** [xvaisr/SINproject#5]
Jak si rozdelime jednotlive casti implementace? @xvaisr  ty si chtel delat ten simulator ze? @OndrejBlucha prosim vyber si na ktere casti by te bavilo pracovat, ja udelam zbytek. Ale hlavne zacneme uz tento vikend psat, dejme tomu prvni commit do pondeli? Aspon s nastrelem reseni vybrane casti projektu.

**Comment by xvaisr** [comment]
nastrel klinde napisu, ale na commit do pondeli zapomen ... ucim se na MAT. Do konce tydne abych ale mel byt schopny neco zpatlat. Kazdopadne jsem rad, ze jsi aktivni ...
