### ISSUE TITLE
Project demonstration registration

### ISSUE THREAD

**Issue by trepik** [xvaisr/SINproject#6]
The registration opens 2016-12-01 08:00:00 and there are 6 time-slots we can register for. The bad news is that I'm only available Tuesday 4PM. Is it ok with you?

**Comment by xvaisr** [comment]
I am ok at that time ...How about  @OndrejBlucha

**Comment by trepik** [comment]
I asked him directly at school and hes fine with that as well, will you do the registration?

**Comment by xvaisr** [comment]
2016-12-06 16:00 A211 registrováno ...
